"""add fields_schema and custom_responses

Revision ID: 4a5631ac88d1
Revises: 62b427f3710f
Create Date: 2026-07-18 07:33:38.187299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5631ac88d1'
down_revision: Union[str, Sequence[str], None] = '62b427f3710f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aduan_services', sa.Column('fields_schema', sa.JSON(), nullable=True))
    op.add_column('tickets', sa.Column('custom_responses', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'custom_responses')
    op.drop_column('aduan_services', 'fields_schema')
    # ### end Alembic commands ###
