"""persist_order

Revision ID: 62b427f3710f
Revises: 983eb7a7e536
Create Date: 2026-07-18 05:16:12.519117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b427f3710f'
down_revision: Union[str, Sequence[str], None] = '983eb7a7e536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('position', sa.Integer(), nullable=True))
    op.execute("UPDATE tickets SET position = 0")
    op.alter_column('tickets', 'position', nullable=False)
    op.add_column('workspaces', sa.Column('status_order', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'status_order')
    op.drop_column('tickets', 'position')
    # ### end Alembic commands ###
