"""add_ticket_number

Revision ID: 76ca6d6e8433
Revises: b5cbddf320e2
Create Date: 2026-07-17 22:16:51.589960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ca6d6e8433'
down_revision: Union[str, Sequence[str], None] = 'b5cbddf320e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('number', sa.Integer(), nullable=True))
    op.execute("UPDATE tickets SET number = 1")
    op.alter_column('tickets', 'number', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'number')
    # ### end Alembic commands ###
