"""add aduan service

Revision ID: 983eb7a7e536
Revises: 76ca6d6e8433
Create Date: 2026-07-18 02:44:43.735733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983eb7a7e536'
down_revision: Union[str, Sequence[str], None] = '76ca6d6e8433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aduan_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aduan_services_slug'), 'aduan_services', ['slug'], unique=True)
    op.add_column('tickets', sa.Column('aduan_service_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('creator_email', sa.String(), nullable=True))
    op.create_foreign_key('fk_tickets_aduan_service_id', 'tickets', 'aduan_services', ['aduan_service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tickets_aduan_service_id', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'creator_email')
    op.drop_column('tickets', 'aduan_service_id')
    op.drop_index(op.f('ix_aduan_services_slug'), table_name='aduan_services')
    op.drop_table('aduan_services')
    # ### end Alembic commands ###
