"""add require_login to aduan_services

Revision ID: d9dbafc7a450
Revises: 4a5631ac88d1
Create Date: 2026-07-18 10:14:55.650014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dbafc7a450'
down_revision: Union[str, Sequence[str], None] = '4a5631ac88d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('aduan_services', sa.Column('require_login', sa.Boolean(), nullable=True))
    op.execute("UPDATE aduan_services SET require_login = FALSE")
    op.alter_column('aduan_services', 'require_login', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aduan_services', 'require_login')
    # ### end Alembic commands ###
